### ISSUE TITLE
Publish the API builds somewhere

### ISSUE THREAD

**Issue by alkurbatov** [cpp-sc2/cpp-sc2#1]
- [ ] Publish at least Windows builds.
- [ ] Add link to the files to README.

**Comment by yanntm** [comment]
ok so I can do that also with a bit more travis magic, principle is each build uploads to a different branch instead of gh-pages, then we link the artifacts using ...?/raw/ in the url to the file and people can download it. I'll build a PR with it when the doxygen thing is stable.

**Comment by alkurbatov** [comment]
That would be very cool, thank you! :)
But which place should be used to store the data? This is the main problem which stoped me from implementing this feature. As far as I understood GitHub actions doesn't provide storage unfortunately.
We may ask AIArena devs for hosting but I am not sure.

**Comment by yanntm** [comment]
they go to github, into branches that only contain the artifact, the links I posted use this to build the osx artifact : https://github.com/lip6/libDDD/blob/master/.travis.yml#L65 this sets the deploy to go to another branch than gh-pages (the default)

**Comment by alkurbatov** [comment]
Git is pretty bad at storing binary artefacts. It would be much better to put those file on some kind of storage.

**Comment by yanntm** [comment]
well we don't keep history of the binaries, the point is mostly to host everything in the same place on github. Git is not great at binaries, but Github is great at providing us scaleable storage/distribution platform. They put a limit on artifact size at 100 MB files/1 GB total, which is enough for this easily.
We could publish an archive like the one that existed in "Precompiled libs" of https://github.com/Blizzard/s2client-api readme, for each OS. These would be snapshots, in sync with latest "master".
I believe there is also a way to deploy to github "releases" for longer term storage, but perhaps this can be done manually after tagging the release.

**Comment by alkurbatov** [comment]
I understand, but if we simply 'commit' new data, the repository will bloat. If we do things like rebase+force-push, it could be better, but we will lost possibility to provide different versions of the API for different game clients. I would like to support this feature and let developer decide which version he want to use. Such approach also allows us e.g. to keep several branches (one branch per game version) and do specific fixes there. As a result, it is more flexible.

**Comment by yanntm** [comment]
I'll prototype a version on my fork, that provides Release versions for the three platforms. We can always  store artifacts on a named branch like 1.1_win to keep versions or use the "release" feature of gh.

**Comment by yanntm** [comment]
i'll build artifacts with a time stamp cpp-sc2.1.2.0.201909101240 as snapshots we can discuss how to archive the versions that are considered stable

**Comment by yanntm** [comment]
first attempt visible here https://github.com/yanntm/cpp-sc2/tree/linux, by browsing linux or osx branches. The deployment for win is still failing (some / or \ path issue it seems).
I just dumped the whole build/ folder to gh in this version.
Is there a "make install" or "make dist" we can invoke to package the headers and stuff into a folder structure like the artifact/zip blizz distributed ?

**Comment by alkurbatov** [comment]
>Is there a "make install" or "make dist"

Unfortunately, no, it should be implemented in cmake by hand.

To be honest I am not fan of storing binary data in git as git is for code, not for artifacts. I would rather pay for files hosting instead or host it on my machine. So I suggest not hurry on implementation of this ticket.

**Comment by alkurbatov** [comment]
Also, in case of Linux it would be much better to provide a RPM package.

**Comment by yanntm** [comment]
so there is this CPack tool for building distributions apparently as msi/rpm if that is what we want to go for.
https://gitlab.kitware.com/cmake/community/wikis/doc/cpack/PackageGenerators
but it is not configured currently, and I've no familiarity with it (I use automake not cmake)
Still, it seems pretty easy to set up, just basically cite what files you want to grab (for us we want include/ lib/ and the simple bot example with sources).
The hosting and the building of a package are two different issues, travis has many other deployment adapters if you really don't like leveraging gh to host us in this manner.

**Comment by alkurbatov** [comment]
cmake shouldn't trigger neither msi, nor rpm builds, although it is possible, but some third-party build system should. Also, manual publishing of packages could be an option, too, as we don't build packages each night.

>But I've been using this branches mechanism to hold my artefacts for at least a couple years now, with history crushing activated, there is no bad bloating issue for the repo imho.

There is nothing that could broke, it just increases the size of your repo, as every version of binary is stored somewhere as is and there is no way to transfer only changes like git usually do with the text files. I got nice experience of conversion of SVN repos with binary files to git repo. A single repo could be like 200 MB during checkout. Of course there are several ways to decrease the size, including aggressive history modification, but I would rather avoid it.

I need to think more about it, that's why I suggest to postpone further activity in this issue.

**Comment by m1ndgames** [comment]
>  We may ask AIArena devs for hosting but I am not sure.
No problem, you could also automate the deploy using scp or something.

**Comment by alkurbatov** [comment]
Fixed in add73174331da797e808c37b2c96933e8153e5cf
