### ISSUE TITLE
BuildBarracksTechLabDifferentPoint failed

### ISSUE THREAD

**Issue by emyr666** [cpp-sc2/cpp-sc2#104]
**Describe the bug**
Missing an order in a unit definition?

**To Reproduce**
Build and install then run 'all_tests' in the bin directory

it prints 

Test: 3sc238TestBuildBarracksTechLabDifferentPointE failed!
    Error: Expected order not in unit orders

**Expected behavior**
This test should not fail

**Desktop (please complete the following information):**
 - OS / Distro: macOS big sur 11.5.2
 - cpp-sc2 Version: commit c295c562ecdd3bbd773b53d7311116c6e34c3cf5
 - StarCraft II version5.0.7

**Comment by alkurbatov** [comment]
Hi @emyr666 
Thank you for reporting the issue. Unfortunately, this is known problem appeared after the one of the breaking patches. So far I have no idea how to handle it.

**Comment by Nickrader** [comment]
After some sleuthing, it seems 'test_unit_command.cc', line 194 should be 'TERRAN_BARRACKSFLYING'.
As currently there are no orders on the TERRAN_BARRACKS.
As TERRAN_BARRACKSFLYING we get 2 orders: land, build_techlab.

With test set to 'realtime', we can see this barracks is flying to get to a different point.

I used this addition of code in 'test_unit_command_common.cc' to verify one had orders and the other did not.
Starting line 84:
```
void TestUnitCommand::VerifyUnitOrders(const Unit* unit, ABILITY_ID test_ability) {
        bool order_found = false;
        
###            for (UnitOrder order : unit->orders) {
###                std::cout << "Order_Ability_Id: " << order.ability_id << std::endl;
###                std::cout << "Test_Ability_Id: " << AbilityTypeToName(test_ability) << std::endl;
```
I'll try and get a PR done soon, if no one else does, but I stayed up too late investigating to do it tonight/this morning.

**Comment by alkurbatov** [comment]
Great! Thank you, looks like this is the source of the issue.

**Comment by alkurbatov** [comment]
Closed, as the issue was fixed.
