### ISSUE TITLE
Question about running multiple game processes in parallel

### ISSUE THREAD

**Issue by BaiChunhui-9803** [cpp-sc2/cpp-sc2#123]
Hello.
I run the API on Linux Ubuntu 20.04.3. How am I supposed to create multiple different game processes in parallel? For example, I want to create 10 game processes running independently and then evaluate them. Should I use SetPortStart() to keep the PID of each process different?

**Comment by alkurbatov** [comment]
Hello @BaiChunhui-9803 .
This task is outside of the scope of this API. The API usually assumes that there is only one game process it is interacting with although the code contains some logic which handles several processes for cases when you run both clients from the agent (e.g. you bot plays against builtin AI).

Regarding you task there are at least two ways to solve it:
a. Run game client in advance (i.e. in your code) and attach to it directly.
Example of connecting to a remote client using particular port: https://github.com/cpp-sc2/scrubber/blob/main/src/main.cpp#L41
Also, there is so called LadderManager which solves similar task:
https://github.com/Cryptyc/LadderManagerServer

Note that with this approach you don't have to restart the game client as after the end of each games it is ready to accept new connections. But you still need to manage launch of bot agent somehow.

b. Ask the API to run the game client as usual in each separate instance of a bot agent.
I.e. compile a bot executable and create a routine above it to run 10 copies separately. If I not mistaken the api will pick unoccupied port automatically.

I would suggest to try a.

**Comment by BaiChunhui-9803** [comment]
@alkurbatov Thank you very much for your advice. I'll try these ways.
