### ISSUE TITLE
How can I keep the client open without using `Update()`?

### ISSUE THREAD

**Issue by BaiChunhui-9803** [cpp-sc2/cpp-sc2#125]
Hello.
I want to keep the client open (Even if the game will run without human control, I can reset the state in a game to what I need by using `DebugKillUnit()`, `DebugCreateUnit()` , `DebugSetLife()` and so on) when I break from the loop `while (coordinator.Update()) {}`. And I noticed that the game client will not be closed if I finished debugging the code directly. So How can I keep the client open without using `Update()`?

**Comment by BaiChunhui-9803** [comment]
It takes much less time to connect to an already started client, so I hope the clients won't be closed too often.

**Comment by BaiChunhui-9803** [comment]
Mabey I found the answer, clients will be closed only when the process finishes running.

**Comment by alkurbatov** [comment]
Hi @BaiChunhui-9803 ,
I think your guess is correct. The simplest way is to keep your application running.
