### ISSUE TITLE
Support Visual Studio 2022

### ISSUE THREAD

**Issue by alkurbatov** [cpp-sc2/cpp-sc2#130]
It is said that currently the API doesn't work with the newest Visual Studio. We should support it somehow.

**Comment by Nickrader** [comment]
I had recent problem with `mingw64` being in my path (environment variables).  Something in protobuf build was looking for `unistd.h`, ?abseil?

First error was: Build failed ?protobuf-d.vcxproj ( i forget exact message)

Removing `mysys64/*/mingw*` from path fixed build issues for me, as `zlib` was no longer found by CMake.

Suggest we need output of: 
cmake -B build -G "Visual Studio 17 2022"
and/or
Build -> Solution (in Visual Studio)

to troubleshoot further, as I cannot repro now that I cleaned up my path pollution.

**Comment by alkurbatov** [comment]
Hi, @Nickrader 
I believe it was broken long before integration with mingw. Might be fixed by update of the protobuf submodule, could also require fixes of new compilation issues.

**Comment by Nickrader** [comment]
Yeah, seems to be working now.  Uninstalled 2019, rebuilt 'build' folder, rebuilt in VS.  Examples and tests run. Property pages showing latest release for MSVC, 14.37.32822

**Comment by alkurbatov** [comment]
Done.
