### ISSUE TITLE
Building Linux parallel parameter shell freezes

### ISSUE THREAD

**Issue by Nickrader** [cpp-sc2/cpp-sc2#141]
Documentation, https://github.com/cpp-sc2/cpp-sc2/blob/master/docs/building.md#linux-cmdline ,  shows building using parameter `--parallel`.

This can cause shell to lockup when building protobuf.
`Building CXX object _deps/protobuf-build/CMakeFiles/libprotobuf.dir/src/google/protobuf/compiler/subprocess.cc.o`

Workaround to pass 'n-1' threads your cpu supports to `--parallel` parameter.
E.g. `cmake --build build --parallel -j 7`  assuming your cpu supports 8 threads.

**To Reproduce**
Follow build steps using Linux, leaving '--parallel' as is.

**Expected behavior**
Finish compilation of project

**Desktop (please complete the following information):**
 - OS / Distro:  Ubuntu 23.10

I am assuming this would fall under documentation change?  Or maybe fails elsewhere for others?

**Comment by alkurbatov** [comment]
Updated the documentation.
