### ISSUE TITLE
Unable to build for ladder using wsl2

### ISSUE THREAD

**Issue by nanogeo** [cpp-sc2/cpp-sc2#143]
**Describe the bug**
Build fails with errors saying "This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers. Please regenerate this file with a newer version of protoc."

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Download fresh install of Ubuntu with wsl2
2. Run the following commands:
    1. apt-get update
    2. sudo apt-get install cmake
    3. sudo apt install build-essential
    4. sudo apt install mingw-w64-x86-64-dev  g++-mingw-w64-x86-64  gcc-mingw-w64-x86-64 win-iconv-mingw-w64-dev
    5. sudo update-alternatives --config x86_64-w64-mingw32-gcc
       - Choose option 1
    6. sudo update-alternatives --config x86_64-w64-mingw32-g++
       - Choose option 1
3. Clone blank_bot repo (https://github.com/cpp-sc2/blank-bot)
4. Navigate to said repo
5. Generate CMake configuration with "cmake -B build -DWSL2_CROSS_COMPILE=ON"
6. Compile project with "cmake --build build -j"
7. Observe numerous errors similar to:
```
/mnt/c/Users/hocke/OneDrive/Documents/blank_bot/build/_deps/cpp_sc2-build/generated/s2clientprotocol/debug.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
   17 | #error This file was generated by an older version of protoc which is
      |  ^~~~~
/mnt/c/Users/hocke/OneDrive/Documents/blank_bot/build/_deps/cpp_sc2-build/generated/s2clientprotocol/debug.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
   18 | #error incompatible with your Protocol Buffer headers. Please
      |  ^~~~~
/mnt/c/Users/hocke/OneDrive/Documents/blank_bot/build/_deps/cpp_sc2-build/generated/s2clientprotocol/debug.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
   19 | #error regenerate this file with a newer version of protoc.
      |  ^~~~~
```

**Expected behavior**
The build should finish without errors.

**Desktop (multiple version means multiple attempts with different version):**
 - OS / Distros: Ubuntu 20.04.6/22.04.3
 - cpp-sc2 Version: 1.4.1
 - StarCraft II version 5.0.12
 - GNU Make versions: 4.2.1/4.3
 - CMake version: 3.16.3/3.22.1
 - gcc/g++ version: 9.4.0/11.4.0
 - protoc versions: None/3.12.4/3.23.4/3.23.1

**Additional context**
Tried with different combinations of the flags -DBUILD_FOR_LADDER=ON -DSC2_VERSION=5.0.12 -DSC2_VERSION=4.10.0 but no difference.
Also tried with Ubuntu 24.04 but the package "mingw-w64-x86-64-dev" does not exist for that version of Ubuntu so I could not progress past step 2.4
Also tried building this repo instead of the blank_bot repo with the same steps but encountered the same issue.

**Comment by Nickrader** [comment]
https://github.com/cpp-sc2/cpp-sc2/blob/master/cmake/assets/protos.cmake

Perhaps it has something to do with this?  Included when cross-compile WSL.
https://github.com/cpp-sc2/cpp-sc2/blob/998ca3b1d40013ebb774120787daade8f5f227ea/CMakeLists.txt#L81

**Comment by alkurbatov** [comment]
Unfortunately, this issue is not so simple. This is about updated of precompiled toolchain for WSL2. We provide it as a separate artifact.

**Comment by Nickrader** [comment]
https://github.com/Nickrader/cpp-sc2/tree/wsl_proto
Was able to copy over protos from working windows build and point to that.
Had some trouble with map paths after getting compilation to work.
As a quick fix, could probably zip what I put in /thirdparty/winProto/ to replace old zip

**Comment by alkurbatov** [comment]
But we are speaking about WSL, not regular windows. Please, test build inside it.

**Comment by Nickrader** [comment]
I am away from my windows machine till end of month.  I'm pretty sure I was running it from WSL, after I copied over the protos from windows (as I had to add a Maps folder to my windows Starcraft installation, where I never had to before)
I can test more by August.  
Or if @nanogeo is still around, he could give it a try.  

By the time I got done with the clean install of WSL and fixing what I messed up trying to mimic a normal Linux installation...  
I just figured I'd get it posted for others to see after I got it to work on my system.  It may be as simple as just taking the protos from a working windows build.

From my reading, it appeared that the two approaches were:
    1.  Cross compile on Linux machine using `.configure` command.  Which I didn't attempt or understand yet.
    2.  Compile the protos on Windows and copy it over.  The internet said this was the easier way.

**Comment by Nickrader** [comment]
I'll check when I get back.  when I `diff` what I copied and what builds on linux, they are the same contents.

**Comment by Nickrader** [comment]
After investigation:
* We should be able to use the *.pb.cc, *.pb.h files from any build (using appropriate protoc) to populate the asset. (I can't test mac, but win and linux have same content)

*  To build *.pb.cc/h in WSL: 
* 1) Use a script for a [two-step solution]( https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html#running-executables-built-in-the-project).  "when cross compiling, as the executables are built for the target platform and cannot run on the build host"  In our case, protoc.exe gets built, but compiler wants /bin/protoc.
*  2) Or possibly could link directly to [protoc binary](https://github.com/protocolbuffers/protobuf/releases)

But if we update the asset, we should be good to go for WSL.

**Comment by alkurbatov** [comment]
@Nickrader could you please provide an archive with prebuilt protobuf files + sha of cpp-sc2 commit? Ideally the files you tested wsl build.
 I'll upload the archive to s3.

**Comment by Nickrader** [comment]
https://github.com/Nickrader/cpp-sc2/tree/protos_asset

**Comment by Nickrader** [comment]
I was able to link directly to the precompiled protoc binary.
Everything is a mess at the moment, but I should be able to clean it up in a day or two.
So if you prefer this over the asset.  Big thing to watch out for is that downloaded protobuf version matches linked protoc version.  Otherwise will most likely get a runtime error from google.

https://github.com/Nickrader/cpp-sc2/tree/link_protoc

**Comment by alkurbatov** [comment]
Fixed.
