### ISSUE TITLE
add .clang-format file

### ISSUE THREAD

**Issue by mboedigh** [cpp-sc2/cpp-sc2#52]
I realize the guideline says to use Google style formatting except for 4 space tabs, but this isn't actually the case. For example, Lines are not limited to 80 chars, include files are not always sorted, "private/public:" are at times not indented as in Google, etc. Does it make sense to put a .clang-format file in the source tree Visual Studio document formater can be used without fear of munging the code? 

```
BasedOnStyle:  Google
IndentWidth:   4
ColumnLimit: 0
# AlignConsecutiveAssignments: true  # I like this, but I'm not sure you'd agree. It sometimes requires an extra blank line to make it pretty
# AlignConsecutiveDeclarations: true  # as above

SortIncludes: false
...
```

**Comment by alkurbatov** [comment]
Thank you, this is definitely good idea.

Unfortunately, the repo doesn't really follow the style. In another project I use Google linter to check the style, it could be applied here, too, if the style will be corrected someday.
See https://github.com/alkurbatov/suvorov-bot/blob/master/.travis/lint.sh

**Comment by mboedigh** [comment]
I wasn’t thinking about rejecting code if it didn’t conform. But, over time, every file that gets edited would be Google-like formatted just once. Currently some of the files are sadly out of conformance. Do you mind, if the files I PR have been formatted using the file I proposed?

**Comment by alkurbatov** [comment]
If we want certain style to be used, linter is must have option.
So far the rule is not strict so I don't enforce the style, but Google style is preferred.

**Comment by alkurbatov** [comment]
Done.
The Google style applied with several minor tweaks.
