### ISSUE TITLE
Proposal to add net damage to OnUnitDamaged events

### ISSUE THREAD

**Issue by mboedigh** [cpp-sc2/cpp-sc2#59]
I propose changing the callback to OnUnitDamaged(const Unit *unit, float damage)
This would replace the existing function which does not include damage. Including the amount of damage is useful in a number of situations. For example, inferring what shot you, or calculating how many SCVs you might need to overcome the damage per frame.  

Thoughts?

**Comment by alkurbatov** [comment]
Good idea, would be nice to have. Thank you for suggestion :)

**Comment by alkurbatov** [comment]
Could be useful to add a shield damage, too.

**Comment by mboedigh** [comment]
So maybe 

1) `OnUnitDamaged( unit const *, float damage_health, float damage_shields)` 

would be clearer and better than

2) `OnUnitDamaged( unit const *, float net_damage)`

**Comment by alkurbatov** [comment]
`OnUnitDamaged( unit const *, float damage_health, float damage_shields)`
Looks good to me.

**Comment by ImpulseCloud** [comment]
@alkurbatov This issue was done at some point and can be closed.
