### ISSUE TITLE
IsUnit not defined Tutorial #3

### ISSUE THREAD

**Issue by Nickrader** [cpp-sc2/cpp-sc2#79]
I am new to coding, so may be obvious 'me problem'?  I don't know. 

When I copy paste the full code for Tutorial 3, https://github.com/cpp-sc2/cpp-sc2/blob/master/docs/tutorial3.md ,

`Line 49:  return Observation()->GetUnits(Unit::Alliance::Self, IsUnit(unit_type)).size(); ; `

`IsUnit` (filter) is undefined.

Per the suggestion of VS2019 ( show potential fixes)

I added, 
`#include <sc2api\sc2_unit_filters.h>`
Seems to work normally, compiles without errors.

*If I include `<botexamples.cc>` I get multiple definition errors.
*Including either of the `<sc2_unit_filters>` options, results in working code.

 - Windows 8.1
 - cpp-sc2 Version: 1.3.1
 - StarCraft II version 4.12.0.80188

**Comment by Nickrader** [comment]
Alternatively, 
If I append the `<sc2api\sc2_api.h>` header with 
`#include "sc2_unit_filters.h"` , then no modification of tutorial is needed
on my machine.

**Comment by alkurbatov** [comment]
Hi @Nickrader .
Thank you for the report. The `IsUnit` was moved to `#include "sc2_unit_filters.h` but tutorial hasn't been updated.

**Comment by Nickrader** [comment]
#81 Not sure if this is what is wanted.  My first PR, so please advise on things to do differently.   I assume that the desired fix was in documention and not by appending the header files.

**Comment by alkurbatov** [comment]
Fixed in 3d3fcbbebffdfec590255bc62f5531d3a6904374
