### ISSUE TITLE
Camera no longer moves when clicking minimap

### ISSUE THREAD

**Issue by mboedigh** [cpp-sc2/cpp-sc2#83]
**Describe the bug**
The camera moves with arrow keys, but does not move when clicking minimap. Other mouse actions such as unit selection still work with the mouse and the selection is still reflected in the main window. 

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Start any game from the debugger and set a breakpoint in the OnGameStart() function
2. Try moving the camera by clicking on the minimap

**Desktop (please complete the following information):**
 - OS / Distro: [Windows 10]
 - cpp-sc2 Version: SHA 3bd046938ac3e510655fb26ca8816e6872f36d85, 
 - StarCraft II version [Base81009]

**Additional context**
The cpp-sc2 versions is older, and I don't think the problem stems from there. Can you let me know if you can reproduce? Otherwise, it could be OpenCv, that added relatively recently, or a Blizzard update, or ...

**Comment by RaphaelRoyerRivard** [comment]
Does your problem only happen if you have a breakpoint in OnGameStart()? If put your breakpoint later when the game is started, does the minimap work? I haven't put a breakpoint in OnGameStart() for a long time but I know that it works when I use breakpoints later on, though I haven't tried in sc2 version 5.

**Comment by mboedigh** [comment]
Unfortunately, the problem still occurs after OnGameStart() as well. If anyone has tried this without a problem, on the same version of sc2 please let me know, and I'll conclude it is something weird in my setup.

**Comment by RaphaelRoyerRivard** [comment]
On the sc2ai discord, people have confirmed the problem. Some people think it is not a bug but rather intented by Blizzard to counter cheaters. I'm not sure about that since the ladder games are realtime and the problem doesn't seem to occur in realtime.

**Comment by mboedigh** [comment]
Thanks
