### ISSUE TITLE
EFFECT_STIM does not harm units

### ISSUE THREAD

**Issue by mboedigh** [cpp-sc2/cpp-sc2#85]
**Describe the bug**
When marines use their stim ability, they should be lose 10 health, but this is not always the case
 
**To Reproduce**
 At some time during a game (e.g.  `OnGameStart()`) set `Debug()->DebugIgnoreResourceCost();` and then `SendDebug();`
Create marines, barracks and barracks techlab. Then research Stimpack. After it completes use the stimpack ability on the marines. 

**Expected behavior**
Marines should lose health, but they do no. They are still stim'ed though as can be seen in the in-game unit panel

**Desktop (please complete the following information):**
 - OS / Distro: Windows 10/build 19041
 - cpp-sc2 Version: [e.g. 1.3.1]
 - StarCraft II version Base81433

**Additional context**
Marines are damaged as expected when DebugIgnoreResourceCost() is not used. Strange beans!
the zip file contains an example.
[test_stim.zip](https://github.com/cpp-sc2/cpp-sc2/files/5471612/test_stim.zip)

Please let me know if you can reproduce.

**Comment by ImpulseCloud** [comment]
This is true, @mboedigh. The 10 health is a ResourceCost, so ignoring ResourceCost ignores the health cost. This is an expected effect of IgnoreResourceCost.

I agree it would be nice to test battle outcomes with Stim still costing 10 health (while training everything for free), but that would take additional coding by Blizzard to exclude health costs for abilities (like a new DebugIgnoreResourceCostExceptHealthCosts), and that is done *inside* the Game Engine, not in the outside API, and Blizzard doesn't really support this much anymore, so it won't happen. You can still post in the official https://github.com/Blizzard/s2client-proto about it, but as you can see there are very many unanswered requests.

This issue can be closed. (it's working as intended and not an API issue) Thanks!

**Comment by RaphaelRoyerRivard** [comment]
You can also spawn the Marines and give all upgrades with debug commands
instead of producing them and researching it yourself. It is much faster.

Le jeu. 18 mars 2021 à 12:36, Michael Holtan ***@***.***> a
écrit :

**Comment by ImpulseCloud** [comment]
@mboedigh Using DebugGiveAllResources when you are low on min/gas should achieve the same results, if you are just trying to create large army battles easily.

Though there might be something the API could add.
Currently there is DebugIgnoreMineral() which ignore Mineral cost, but sc2Protocol also has 'gas' in the DebugGameState Enum, that the API doesn't use.
So I think the API could add a DebugIgnoreGas() which ignore gas costs, if you are trying to build armies without costs.

Then I think you can turn on all of IgnoreMinerals + IgnoreGas + IgnoreFood to achieve training without cost. (though there will still be Energy costs for abilities)

It looks like 'gas' is the only one in the Enum that was not given a Debug command.

```
enum DebugGameState : int {
  show_map = 1,
  control_enemy = 2,
  food = 3,
  free = 4,
  all_resources = 5,
  god = 6,
  minerals = 7,
  gas = 8,
  cooldown = 9,
  tech_tree = 10,
  upgrade = 11,
  fast_build = 12
};
```

**Comment by mboedigh** [comment]
Thanks everyone.

**Comment by alkurbatov** [comment]
@ImpulseCloud please file another issue to add missing command/parameter, if needed.
