### ISSUE TITLE
Orders received 2 game loops after SendAction()

### ISSUE THREAD

**Issue by mboedigh** [cpp-sc2/cpp-sc2#86]
**Describe the bug**
When the participants are a Bot (`CreateParticipant`) and an Computer (`CreateComputer`), the effect of stim takes place in the game loop immediately after the game loop in which the action was sent. But, when the participants are two bots, the effect of stim takes place one game loop later.  

**To Reproduce**
See the attached example. It is set up to show the delay. You can uncomment the code to compare to the usual effects of stim. 

**Expected behavior**
A brief description of what should happen.

```   
// When using this setup, the effect of stim is delayed one loop after the next game loop
StimBot bot1;
StimBot bot2;
coordinator.SetParticipants({CreateParticipant(sc2::Race::Terran, &bot1),
                                 CreateParticipant(sc2::Race::Terran, &bot2)});

// When using this setup, the effect of stim happens the next game loop
    coordinator.SetParticipants({CreateParticipant(sc2::Race::Terran, &bot1),
                                 CreateComputer(sc2::Race::Random, sc2::Difficulty::VeryEasy)});

```

**Desktop (please complete the following information):**
 - OS / Distro:  Windows 10
 - cpp-sc2 Version:  1.3.1
 - StarCraft II version: Base81433

[test_stim.zip](https://github.com/cpp-sc2/cpp-sc2/files/5471650/test_stim.zip)

**Comment by alkurbatov** [comment]
Hi, @mboedigh . IT looks more like the game issue to me as there is no specific handling of such commands on the API side.

**Comment by mboedigh** [comment]
Thanks. I was worried that would be the case and was hoping there was some magic work-around. It has a surprisingly devastating effect on the performance of my bot's micro.

**Comment by RaphaelRoyerRivard** [comment]
I can confirm, it's really annoying to have to take that lag into account.
