### ISSUE TITLE
Include sc2api/sc2_unit_filters.h in Tutorial 3

### ISSUE THREAD

**Issue by Naratzul** [cpp-sc2/cpp-sc2#94]
Hello! There is one problem with [Tutorial 3](https://github.com/cpp-sc2/cpp-sc2/blob/master/docs/tutorial3.md).

In order to use filter predicates (such a IsUnit) we have to include additional header "sc2_unit_filters.h". Otherwise example from this tutorial will not compile.  We can also include that header to "sc2_api.h".

**Comment by alkurbatov** [comment]
Hi @Naratzul! Thank you for reporting the issue.
This problem was fixed in https://github.com/cpp-sc2/cpp-sc2/commit/3d3fcbbebffdfec590255bc62f5531d3a6904374 in the dev branch.
