### ISSUE TITLE
Allow ActionImp::UnitCommand to use sc2::Tag instead of sc2::Unit*

### ISSUE THREAD

**Issue by ImpulseCloud** [cpp-sc2/cpp-sc2#96]
**Is your feature request related to a problem? Please describe.**
If we want to issue a command and we have a Unit Tag, we have to make a dummy Unit to put the Tag in and pass it.

**Describe the solution you'd like**
Add versions of ActionImp::UnitCommand in sc2_agent.cc that use sc2::Tag instead of sc2::Unit*/Units&

**Comment by Nickrader** [comment]
Okay, I think I've got it.  I was going down the wrong path, thanks.  I'll give it a fresh look and a cleanup tomorrow.

**Comment by Nickrader** [comment]
Closed by #111 ; I didn't link in the PR.
